app/main/forms.py
# encoding:utf8
from flask.ext.wtf import Form
from wtforms import StringField,SubmitField, FieldList, SelectField,\
        PasswordField
from wtforms.validators import Required, Length
import wtforms
from ..models import Address

class UserForm(Form):
    phoneNumber = StringField(u"手机号",validators=[Required()])
    password = PasswordField(u"密码",validators=[Required(), Length(min=6, max=15)])
    verification = StringField(u"验证码", validators=[Required()])
    nickName = StringField(u"昵称")
    addresses = SelectField(u"",choices=[], coerce=int)
    submit = SubmitField(u"提交")

class LoginForm(Form):
    phoneNumber = StringField(u"手机号",validators=[Required(), Length(min=11, max=11)])
    password = PasswordField(u"密码", validators=[Required()])
    submit = SubmitField(u"提交")

class SMSForm(Form):
    phoneNumber = StringField(validators=[Required(), Length(min=11, max=11)])

class OrderForm(Form):
    actualMealID = FieldList()
    submit = SubmitField(u"闪电抢食")

class ChangePasswordForm(Form):
    phoneNumber = StringField(u"手机号",validators=[Required()])
    oldPassword = PasswordField(u"旧密码",validators=[Required(), Length(min=6, max=15)])
    newPassword = PasswordField(u"新密码",validators=[Required(), Length(min=6, max=15)])
    submit = SubmitField(u"提交")

class ForgotPasswordForm(Form):
    phoneNumber = StringField(u"手机号", validators=[Required(), Length(min=11, max=11)])
    verification = StringField(u"验证码", validators=[Required()])
    password = PasswordField(u"新密码", validators=[Required(), Length(min=6, max=15)])
    submit = SubmitField(u"提交")

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
# coding=utf8
from .. import db
from ..models import User, Address, ActualMeal, Meal, Picture, Order,\
        SMSModel, LikeModel
from flask import render_template, request, redirect, url_for, flash, jsonify
from . import main
from forms import UserForm, LoginForm, SMSForm, ChangePasswordForm,\
        ForgotPasswordForm
from flask.ext.login import current_user, login_user, logout_user,\
        login_required
import flask
import datetime, time
from sqlalchemy import and_, or_
import json
import urllib2, urllib
from ..shareVars import SMS_URL, SMS_ACCOUNT, SMS_PASSWORD
from xml.dom import minidom
import random
from .. import redis
from manage import app

@main.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@main.before_app_request
def before_request():
    # for counting online users
    if current_user.is_authenticated():
        #make_online( current_user.id )
        pass

def Duration_between_times( time1, time2):
    date1 = datetime.datetime.combine(
                datetime.date.today(),
                time1
            )
    date2 = datetime.datetime.combine(
                datetime.date.today(),
                time2
            )
    return (date1 - date2).total_seconds()

@main.route('/', methods=['GET'])
@main.route('/<addressName>', methods=['GET'])
@main.route('/index/', methods=['GET'])
@main.route('/index/<addressName>', methods=['GET'])
def index(addressName = None):
    today_date = datetime.date.today()
    current_datetime = datetime.datetime.now()
    current_time = datetime.time(
               current_datetime.hour,
               current_datetime.minute,
               current_datetime.second,
               current_datetime.microsecond
            )

    addressID = None
    if addressName is not None:
        current_address = Address.query.filter_by( address = addressName ).first()
        if current_address:
            addressID = current_address.id

    if addressID is None:
        if current_user.is_authenticated():
            addressID = current_user.addressId
        else:
            current_address = Address.query.first()

            if current_address:
                addressID = current_address.id

    if addressID is not None:
        current_actualMeal = ActualMeal.query.filter(
                ActualMeal.addressId == addressID,
                ActualMeal.date == today_date).filter(
                    or_(
                        ActualMeal.startTime > current_time,
                        and_(
                            ActualMeal.startTime<= current_time,
                            ActualMeal.endTime >= current_time
                        )
                    )
                ).order_by(ActualMeal.startTime).first()


    #form of login
    loginForm = LoginForm(request.form)

    # form of register
    userForm = UserForm(request.form)
    # set the choices of register form(user form)
    userForm.addresses.choices = [
            (address.id, address.address) for address in Address.query.all()
        ]
    HiddenRegisterForm = UserForm(request.form)
    # set the choices
    HiddenRegisterForm.addresses.choices = [
            (address.id, address.address) for address in Address.query.all()
        ]

    if addressID is None:
        return render_template('index.html',
                userForm = userForm,
                loginForm = loginForm,
                )


    # store the information of this meal, not the actual meal
    mealInformation = None
    if current_actualMeal:
#    calculate the duration between the start time of the next meal
#    and current time
        startDuration = Duration_between_times(
                    current_actualMeal.startTime,
                    current_time
                )
        endDuration = Duration_between_times(
                    current_actualMeal.endTime,
                    current_time
                )

        mealInformation = Meal.query.get( int(current_actualMeal.mealID) )
        mainPicture = Picture.query.filter_by(
            mealId = mealInformation.id, type=0).first()

        mealPicture = Picture.query.filter_by(
            mealId = mealInformation.id, type=1).all()

        materialPicture = Picture.query.filter_by(
            mealId = mealInformation.id, type=2).all()

#    print get_online_users()

    if mealInformation:
        people = random.randint(300, 400)
        return render_template('index.html',
                userForm = userForm,
                loginForm = loginForm,
                meal = mealInformation,
                ameal = current_actualMeal,
                mainPict = mainPicture,
                mealPics = mealPicture,
                materialPics = materialPicture,
                hidden_register_form = HiddenRegisterForm,
                startDuration = startDuration,
                endDuration = endDuration,
                sForm = SMSForm(),
                population = people
                )
    else:
        return render_template('index.html',
                userForm = userForm,
                loginForm = loginForm,
                )

def register_helper_function():
    userForm = UserForm(request.form)
    userForm.addresses.choices = [
            (address.id, address.address) for address in Address.query.all()
        ]
    if userForm.validate_on_submit():
        verificaion_code = userForm.verification.data
        phoneNumber = userForm.phoneNumber.data

        sms_code = SMSModel.query.filter_by(phoneNumber = phoneNumber).first()
        if sms_code.number !=  int(verificaion_code):
            print "sms-code"
            # verification code is incorrect
            return "2"

        nickName = userForm.nickName.data
        addressID = userForm.addresses.data
        password = userForm.password.data
        newUser = User(phoneNumber, nickName, password, addressID)
        db.session.add(newUser)
        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            print e
            return "0"

        # log the uesr in
        user = User.query.filter_by(phoneNumber = phoneNumber).first()
        if user is None:
            return '0'
        else:
            login_user(user, remember = True)
            try:
                db.session.delete( sms_code )
                db.session.commit()
            except:
                db.rollback()
        return '1'
    else:
        print userForm.errors
        return '0'


@main.route('/register', methods=['POST'])
def register():
    registerForm = UserForm(request.form)
    registerForm.addresses.choices = [
            (address.id, address.address) for address in Address.query.all()
        ]
    if registerForm.validate_on_submit():
        phoneNumber = registerForm.phoneNumber.data
        if User.query.filter_by(phoneNumber = phoneNumber).count() != 0:
            #user already exists, jump to log in
            return jsonify( success = 2, msg="手机号已注册, 请直接登录")
        print "try to register"
        result = register_helper_function()
        print result
        if result == "1":
            #register successfully
            return jsonify( success = 1)
        else:
            return jsonify( success = 0, msg="注册失败")
    else:
        print registerForm.errors

    return jsonify( success = 0 )


def loginHelper(phoneNumber, password):
    user = User.query.filter_by( phoneNumber = phoneNumber).first()
    if user is not None and user.verify_password( password ):
        login_user(user, remember=True)
        print "log in success"
        return '1'
    else:
        print 'no such user'
        return '0'


@main.route('/login', methods=['POST'])
def logIn():
    loginForm = LoginForm(request.form)
    if loginForm.validate_on_submit():
        result = loginHelper(
                loginForm.phoneNumber.data,
                loginForm.password.data
                )
        if result == "1":
            return jsonify(success = 1)
        else:
            return jsonify(
                    success=0,
                    msg="用户账号密码错误或者该用户不存在"
            )

    else:
        print loginForm.errors

    return jsonify(
                success=0
            )


@main.route('/logout')
@login_required
def LogOut():
    logout_user()
    return redirect( url_for('main.index') )

@main.route('/like', methods=['POST'])
def Like():
    mealId = request.form['mealId']
    newLike = LikeModel()
    newLike.mealID = mealId
    newLike.userID = current_user.id
    try:
        db.session.add(newLike)
        db.session.commit()
    except Exception as e:
        print e
        return '0'

    return '1'
    pass

def MakeOrderHelperFunction( amealID ):
    newOrder = Order()
    Ameal = ActualMeal.query.get( int(amealID) )
    tempAvailableNumber = 0
#   in case there is no meal
    if Ameal.availableNumber <= 0:
        return '0'
    try:
        Ameal.availableNumber = Ameal.availableNumber - 1
        db.session.add( Ameal )
        db.session.commit()
        tempAvailableNumber = Ameal.availableNumber
    except Exception as e:
        print e
        db.session.rollback()
        print "failed to make order"
        return '0'

    newOrder.userID = current_user.id
    newOrder.amealId = Ameal.id
    newOrder.number = Ameal.amount - tempAvailableNumber
    newOrder.date = datetime.date.today()
    current_time = datetime.datetime.now()

    newOrder.time = datetime.time(
            current_time.hour,
            current_time.minute
    )
    try:
        db.session.add( newOrder )
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        print e
        Ameal.availableNumber = Ameal.availableNumber + 1
        db.session.add( Ameal )
        db.session.commit()
        print "failed to make order"
        return '0'
    return newOrder

def postHelper(url, data):
    req = urllib2.Request( url )
    data = urllib.urlencode( data )

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <!--[if lt IE 9]>
    <script src="{{url_for('static', filename="js/html5.js")}}"></script>
  <![endif]-->
  <title>唯美食</title>
  <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/header.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
</head>
<body>
  <div id = "header">
    <div class = "white-bg">
      <span class = "header-tip">今日特惠：订单号偶数送可乐，尾数为5即免单！
      </span>
    </div>
    <a class = "logo-link"><img class = "logo" src="{{url_for('static', filename='images/logo.png')}}"></a>
    <div id = "nav">
      <ul>
        <li><a ><img  src="{{url_for('static', filename='images/header/menu1-2.png')}}"></a></li>
        <li><a ><img  src="{{url_for('static', filename='images/header/menu2.png')}}"></a></li>
        <li><a ><img  src="{{url_for('static', filename='images/header/menu3.png')}}"></a></li>
        {% if not current_user.is_authenticated() %}
        <li><a><img  src="{{url_for('static', filename='images/header/menu4.png')}}"></a></li>
        {% else %}
        <li class = "logined without">
          <span class = "welcome">欢迎回来~</span> <br />
          <span><span class = "welcome">美食家 </span>
          <span>
            {% if current_user.nickName == "" or current_user.nickName == None%}
              {{current_user.phoneNumber}}
            {% else %}
              {{current_user.nickName}}
            {% endif %}
          </span>
        </span>
         </li>
        {% endif %}
      </ul>
    </div>
    </div>

  {% block body %}
  {% endblock%}

    <script>
      csrftoken = "{{ csrf_token() }}"
    </script>
    <script src="{{url_for('static', filename="js/jquery-1.11.1.min.js")}}">
    </script>
    <script src="{{url_for('static', filename="js/reg_login.js")}}"></script>
    <script src="{{url_for('static', filename="js/main.js")}}"></script>
    <script src="{{url_for('static', filename="js/header.js")}}"></script>
    <script src="{{url_for('static', filename="js/formValid.js")}}"></script>
    <script src="{{url_for('static', filename="js/get-food.js")}}"></script>
    <script src="{{url_for('static', filename="js/forgot-passworld.js")}}"></script>
</body>
</html>

app/templates/change_password.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block body %}
  <div class="container">
    {{wtf.quick_form(cp_form)}}
  </div>
{% endblock %}

app/templates/forgot.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block body %}
  <link rel="stylesheet" href="{{url_for('static', filename='css/success.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/forgot.css')}}">
  <div class="container">
    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{message}}
      </div>
    {% endfor %}
  </div>

  <div  class="result part fogot">
      <h2>忘记密码</h2>
      <form action="{{url_for('main.ForgotPassword')}}" method="POST">
        {{forgot_form.hidden_tag()}}
        {{wtf.form_errors( forgot_form, hiddens="only") }}
        <input class="input-box" id="phoneNumber" name="phoneNumber" value="" type="text" placeholder = "手机号"  maxlength="11"><span class = "tips"></span>
        <br>
        <input class="input-box" id="verification" name="verification" value="" type="text" maxlength = "4" placeholder = "验证码"><span class = "tips"></span>
        <br>
        <button type="button"  id="get_v_code_btn"></button><br>
        <input class="input-box" id="password" name="password" value="" type="password" placeholder = "新密码" maxlength = "16"><span class = "tips"></span>
        <br>
        <input id = "submit" name="submit" type="submit"  class = "forgot-commit" value = ""/><br>
      </form>
  </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block body%}
{% if meal  %}
	{% include "main.html" %}
	{% include "reg_login.html" %}
{% else %}
	<!-- 没有食物界面 begin -->
	<link rel="stylesheet" href="{{url_for('static', filename='css/success.css')}}">
	<div id = "result-faild" class = "part result">
	 <br>
	 <span class = "content4 content4-1">今天已经没有食物了~</span>
	</div>
	<!-- 没有食物界面 end -->
{% endif %}
<!-- register/login part -->
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block body%}

  <div class="container">
    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{message}}
      </div>
    {% endfor %}
  </div>

  <div class="container">
    {% if msg %}
    <p style="color:red">{{msg}}</p>
    {% endif %}
    {{wtf.quick_form(login_form)}}
    <a href="{{url_for("main.register")}}">注册</a>
  </div>
{% endblock %}

app/templates/main.html
<link rel="stylesheet" href="{{url_for('static', filename='css/part1.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='css/part2.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='css/part3.css')}}">
<!-- main demonstration part -->
<div  id="main_container" class = "part"> <!-- main container -->
  <div id="get_meal">
    <span id="mealID" style="display:none;">{{meal.id}}</span>
    {% if mainPict %}
      <img src="{{url_for("static", filename = "pic/" + mainPict.name)}}" class = "meal-pic" alt="">
    {% endif %}
    <div class = "description">
      <span>{{meal.description}}</span>
    </div>
    <div class = "point-chan">
      <span id="likes">{{meal.likes.__len__()}}</span><span class = "chan">赞<span>
      {% if current_user.is_authenticated() %}
          <button id="mealLike" class="btn btn-default chan-button">赞</button>
      {% endif %}
    </div>
  </div> <!-- #getmeal container ends-->
  <div class = "part1-right"> <!-- counting and price container-->
    <!-- price -->
    <div id="price_part">
        <!-- <span>{{startDuration}}</span> -->
        <span id="real_price">￥{{meal.price * meal.discount}}</span>
          {%if startDuration > 0 %} 
            <a class = "get-food-button">
              <button >
                 <img  src="{{url_for('static', filename='images/part1/get-food-before.png')}}">
              </button>
            </a>
          {% else %}
            {% if ameal.availableNumber > 0 %}
              {% if not current_user.is_authenticated() %}
                <a class = "get-food-button no-login-button">
                  <button>
                     <img  src="{{url_for('static', filename='images/part1/get-food.png')}}">
                  </button> 
                </a>
              {% else %}
              <a class = "get-food-button" href="{{url_for('main.MakeOrder', amealID=ameal.id)}} ">
                <button>
                   <img  src="{{url_for('static', filename='images/part1/get-food.png')}}">
                </button> 
              </a>
              {% endif %}
            {% else %}
              <a class = "get-food-button">
                <button >
                   <img  src="{{url_for('static', filename='images/part1/food-out.png')}}">
                </button>
              </a>
            {% endif %}
          {% endif %}

        <div id="price_information">
          <ul>
            <li>
              <span>市场价</span>
              <br>
              <span class = "price_information_num">￥{{meal.price}}</span>
            </li>
            <li>
              <span>折扣</span>
              <br>
              <span class = "price_information_num">{{meal.discount}}</span>
            </li>
            <li>
              <span>为您节省</span>
              <br>
              <span class = "price_information_num">￥{{meal.price * (1 - meal.discount)}}</span>
            </li>
          </ul>

        </div> <!-- #price_information ends-->
    </div><!-- price ends -->
      <!-- counting part -->
        <div id="count_container">
          <!-- <p>倒计时</p> -->
          <div id="start_count" {%if startDuration <= 0 %} style="display:none;"{% endif %}>
            <span class = "time-state">马上就要开抢了</span><br>
            <div class = "time-count">
              <span id="s_hour">
                0
              </span>时
              <span id="s_minute">
                0
              </span>分
              <span id="s_second">
                {{startDuration}}
              </span>秒
            </div>
            <div class = "users"> 
              <span class = "fixed-width">共有{{population}}名</span>
              <br>
              <span>美食家正在等待抢食</span>
            </div>

            <div class = "remain-num">
              <span class = "fixed-width">共有{{ameal.availableNumber}}份</span>
              <br>
              <span>美食将被抢食一空</span>
            </div>

          </div>

          <div id="end_count"  {%if startDuration > 0 %} style="display:none;"{% endif %}>
            <span class = "time-state">距离美食疯狂抢结束 ：</span><br>
            <div class = "time-count">
              <span id="e_hour">
                0
              </span>时
              <span id="e_minute">
                0
              </span>分
              <span id="e_second">
                {{endDuration}}
              </span>秒
            </div>

            <div class = "users"> 
              <span class = "fixed-width">共有<span class = "font-14">{{population}}</span>名</span>
              <br>
              <span>美食家正在疯抢</span>
            </div>

            <div class = "remain-num">
              <span class = "fixed-width">还剩<span class = "detail-num">{{ameal.availableNumber}}</span>份</span>
              <br>
              <span>美食即将售完</span>
            </div>
        </div>
     </div>
    <!-- count part ends -->
  </div><!-- counting and price container ends-->
</div><!-- main container ends-->
<!-- main demonstration part end -->


<!-- 美味佳肴 part -->
<div id="introduction" class = "part">
  <div class = "pic-set">
  {% for pic in mealPics %}
    <img data-src="holder.js/300*300" src="{{url_for('static', filename="pic/" + pic.name)}}" alt="" class="img-rounded img-responsive" >
  {% endfor %}
  </div>
</div>
<!-- 美味佳肴 part ends-->

<!-- Details part -->
<div id="details" class = "part">
  <div class = "pic-set">
    {% for pic in materialPics %}
      <div class = "delicacies-list">
        <img src="{{url_for('static', filename="pic/" + pic.name) }}" alt="" class="img-rounded img-responsive">

         <span class = "detail-description">{{pic.title}}</span>
         <span class = "detail-content">{{pic.description}}</span>

      </div>
    {% endfor %}
  </div>
</div>
<!-- Detalis part ends -->

app/templates/main_backup.html
{% import "bootstrap/wtf.html" as wtf %}


<!-- main demonstration part -->
<div class="col-md-offset-2  col-md-9 container" id="main_container"> <!-- main container -->
  <div id="get_meal" class="container col-md-4 col-xs-4">
    <span id="mealID" style="display:none;">{{meal.id}}</span>
    {% if mainPict %}
      <img src="{{url_for("static", filename = "pic/" + mainPict.name)}}" alt="">
    {% endif %}
    <p>{{meal.description}}</p>
    已有<span id="likes">{{meal.likes}}</span>人点赞
    {% if current_user.is_authenticated() %}
      <button id="mealLike" class="btn btn-default">赞</button>
    {% else %}
      <br>
    {% endif %}
  </div> <!-- #getmeal container ends-->
  <div class="container col-md-4 col-xs-4" > <!-- counting and price container-->
    <!-- counting part -->
    <div id="count_container" class="container">
      <p>倒计时</p>
      <div id="start_count" {%if startDuration < 0 %} style="display:none;"{% endif %}>
        <p style="color:red;">马上就要开抢了</p>
        <span id="s_hour">
          0
        </span>时
        <span id="s_minute">
          0
        </span>分
        <span id="s_second">
          {{startDuration}}
        </span>秒
      </div>
      <div id="end_count" {%if startDuration > 0 %} style="display:none;"{% endif %}>
        <p style="color:red;">疯狂抢购吧</p>
        <span id="e_hour">
          0
        </span>时
        <span id="e_minute">
          0
        </span>分
        <span id="e_second">
          {{endDuration}}
        </span>秒
    </div>

    </div>
    <!-- count part ends -->

    <!-- price -->
    <div id="price_part" class="container col-md-8">
        <span id="real_price">￥{{meal.price * meal.discount}}</span>

        {% if ameal.availableNumber > 0 %}
          {% if current_user.is_authenticated() %}
            <button id="get_meal_after_login" class="getButton btn btn-default" {% if startDuration > 0 %}style="display:none;"{% endif %}>
              闪电抢食
            </button>
            <form action="POST" style="display:None;" id="get_meal_confirm_form" role="form">
              <div class="form-group">
                <input type="text" style="display:None" name="amealId" value="{{ameal.id}}">
                <input type="text" style="display:None" name="phoneNumber" value="{{current_user.phoneNumber}}">
                输入密码: <input type="password" name="password" class="form-control" type="text">
                <button type="button" id="get_meal_confirm_button" class="btn btn-default">确认</button>
              </div>
            </form>
          {% else %}
            <form action="POST" style="display:None;" id="get_meal_without_log_form">
              {{hidden_register_form.hidden_tag()}}
              <h3>订单信息</h3>
              手机号:{{hidden_register_form.phoneNumber(class="form-control")}} <br/>
              昵称:{{hidden_register_form.nickName(class="form-control")}}
              <br>
              密码:{{hidden_register_form.password(class="form-control")}}
              <br>
              地址:{{hidden_register_form.addresses(class="form-control")}}
              <br>
              <button type="button" id="get_meal_without_log_confirm_button" class="btn btn-default">
                确认
              </button>
            </form>
            <button id="get_meal_without_login" class="getButton btn btn-default" {% if startDuration > 0 %}style="display:none;"{% endif %}>
              闪电抢食
            </button>
          {% endif %}
        {% else %}
          <p>很遗憾，已经全部被抢完了╮(╯▽╰)╭</p>
        {% endif %}
        <div id="price_information">
          <p>市场价:{{meal.price}}</p>
          <p>折扣:{{meal.discount}}</p>
          <p>为你节省:{{meal.price * (1 - meal.discount)}}</p>
          <p>还剩:{{ameal.availableNumber}}份</p>
        </div> <!-- #price_information ends-->
    </div><!-- price ends -->
  </div><!-- counting and price container ends-->
</div><!-- main container ends-->
<!-- main demonstration part end -->
<hr>

<!-- 美味佳肴 part -->
<div id="introduction" class="container col-md-offset-2">
  <h2>Introduction 美味佳肴</h2>
  {% for pic in mealPics %}
  <a href="#" class="thumbnail">
    <img data-src="holder.js/300*300" src="{{url_for('static', filename="pic/" + pic.name)}}" alt="" class="img-rounded img-responsive" >
  </a>
  {% endfor %}
</div>
<!-- 美味佳肴 part ends-->
<hr>

<!-- Details part -->
<div id="details" class="container col-md-offset-2">
  <h2>Details 山珍海味</h2>
  {% for pic in materialPics %}
  <a href="#" class="thumbnail">
    <img src="{{url_for('static', filename="pic/" + pic.name) }}" alt="" class="img-rounded img-responsive">
  </a>
  {% endfor %}
</div>
<!-- Detalis part ends -->
<hr>

app/templates/make_order.html
{% extends "base.html" %}
{% block body %}
  {% if userForm and loginForm %}
    {% include "reg_login.html" %}
  {% endif %}
{% endblock %}

app/templates/reg_login.html
{% import "bootstrap/wtf.html" as wtf %}

<link rel="stylesheet" href="{{url_for('static', filename='css/part4.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='css/reg-login.css')}}">
{% if not current_user.is_authenticated() %}
<div id="reg_login" class="part">
  <div class = "reg-login-left">
    {% if mainPict %}
      <img src="{{url_for("static", filename = "pic/" + mainPict.name)}}" class = "meal-pic" alt="">
    {% endif %}
  </div>
<div class = "reg-login-right">
    <button type="button"  name="t_reg_btn" class = "reg-btn reg-login-btn"></button>
    <button type="button"  name="t_log_btn" class = "login-btn reg-login-btn"></button>
    <form method="POST"
      {% if request.args.next %}
        action="/register?next={{request.args.next}}"
      {% else %}
        action="/register"
      {% endif %}
      id="register_form" class="" role="form">
      <div class="form-group">
        {{userForm.hidden_tag()}}
      <input type = "text" placeholder = "手机号" class = "input-box" name="phoneNumber" id="phoneNumber" maxlength = "11" /><span class = "tips"></span>
      <input type = "password" placeholder = "密码" class = "input-box" name="password" id="password"/><span class = "tips"></span>
      <br>
      <input type = "text" placeholder = "短信验证码" class = "input-box" name="verification" id="verification"/><span class = "tips"></span>
      <button type="button"  id="get_v_code_btn"></button>
      <br>
      <input type = "text" placeholder = "昵称" class = "input-box" name="nickName" id="nickName"/>
      <br>
      <!-- <select class = "select-box">
        <option selected = "selected">中山大学</option>
      </select> -->
      {{wtf.form_field(userForm.addresses,class = "select-box" )}}
      <div  class = "last-step"></div><span class = "tips regist-tip"></span>
        <!-- <button type="button" id="register_button" class="btn btn-default">提交</button> -->
      </div>
    </form>

    <form method="POST" id="loginForm"
      {% if request.args.next %}
        action="/login?next={{request.args.next}}"
      {% else %}
        action="/login"
      {% endif %}
      style="display:none;">
      <div class="form-group">
         {{loginForm.hidden_tag()}}
        <input type = "text" placeholder = "手机号" class = "input-box" id="phoneNumbaer" name="phoneNumber" maxlength = "11"/><span class = "tips"></span>
        <input type = "password" placeholder = "密码" class = "input-box" id="loginpassword" name="password"/><span class = "tips"></span>
        <br />
        <div  class = "commit"></div><span class = "tips"></span>
        <!-- <button id="loginButton" type="button" class="btn btn-default">提交</button> -->
      </div>
    </form>
    <a href="{{url_for('main.ForgotPassword')}}">忘记密码</a>
</div>
</div>
{% endif %}

app/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block body %}
  <div class="container">
    {% if register_form %}
    <form method="POST" role="form" class="form">
      {{register_form.hidden_tag()}}
      {{wtf.form_field(register_form.phoneNumber)}}
      {{wtf.form_field(register_form.password)}}
      {{wtf.form_field(register_form.verification)}}
      {{wtf.form_field(register_form.nickName)}}
      {{wtf.form_field(register_form.addresses)}}
      {{wtf.form_field(register_form.submit)}}
      <button type="button" class="btn btn-default" id="get_v_code_btn">获取验证码</button>
    </form>
    {% endif %}
  </div>
{% endblock %}